/*
 * Copyright (C) 2012-2025 MotionSystems
 * 
 * This file is part of ForceSeatMI SDK.
 *
 * www.motionsystems.eu
 *
 */

using System;
using System.Runtime.InteropServices;

namespace MotionSystems
{
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	public struct FSMI_SFX_Effect
	{
		// Effect type. It is one of FSMI_SFX_EffectType.
		public byte type;

		// Area where the effect should be generated. It is combination of FSMI_SFX_AreaFlags.
		public ushort area;

		// Frequency (Hz) of the effect, from 0 to 255. Not all effects support all frequencies.
		// - SinusL2: 0 to 100
		// - SinusL3: 0 to 100
		// - SinusL4: 0 to 100
		public byte frequency;

		// Amplitude of the effect, from -1 to 1. Not all effects support full amplitudes.
		// - SinusL2: -0.12 to 0.12
		// - SinusL3: -0.12 to 0.12
		// - SinusL4: -0.12 to 0.12
		public float amplitude;

		// For future use
		public byte reserved1;
		public byte reserved2;
		public byte reserved3;
		public byte reserved4;
		public byte reserved5;
		public byte reserved6;
		public byte reserved7;
		public byte reserved8;
	}

	///
	/// This structure defines special effects that are generated by the hardware and are independent to
	/// the primary telemetry or positioning data stream. Not all devices support this feature.
	///
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	public struct FSMI_SFX
	{
		// Put here sizeof(FSMI_SFX).
		// NOTE: This field is mandatory.
		public byte structSize;

		// Number of the effects specified in the below filed. From 0 to FSMI_SFX_MaxEffectsCount.
		public byte effectsCount;

		[MarshalAs(UnmanagedType.ByValArray, SizeConst = (int)FSMI_Defines.SFX_MaxEffectsCount)]
		public FSMI_SFX_Effect[] effects;

		// Helper method to create a structure with preallocated space for nested structures
		public static FSMI_SFX Prepare()
		{
			var sfx        = new FSMI_SFX();
			sfx.structSize = (byte)Marshal.SizeOf(sfx);
			sfx.effects    = new FSMI_SFX_Effect[(int)FSMI_Defines.SFX_MaxEffectsCount];
			return sfx;
		}
	}

	public enum FSMI_SFX_EffectType
	{
		// Effect is appended to the required position before trajectory generator uses the position.
		// It means that this effect affects state of the adaptive algorithms which are used to adjust motion platform
		// operation parameters to the signal dynamics. This effect might be also less pronounced if trajectory generator
		// is configured to use long acceleration ramps.
		// It is supported only by "PS" and "QS" motion platforms.
		SinusLevel2 = 0,

		// Effect is appended to the output (position) of the trajectory generator. It is NOT affected by the
		// trajectory generator configuration and it does NOT affect the adaptive algorithms. Result of this effect
		// might be different depending on the actuator hardware configuration (length/pitch).
		// It is supported only by "QS" motion platforms.
		SinusLevel3 = 1
	};

	public struct FSMI_SFX_AreaFlags
	{
		// Effect is generated on the actuator(s) assigned to the front-left area of the cockpit.
		public const int FrontLeft  = 1 << 0;

		// Effect is generated on the actuator(s) assigned to the front-right area of the cockpit.
		public const int FrontRight = 1 << 1;

		// Effect is generated on the actuator(s) assigned to the rear-left area of the cockpit.
		public const int RearLeft   = 1 << 2;

		// Effect is generated on the actuator(s) assigned to the rear-right area of the cockpit.
		public const int RearRight  = 1 << 3;

		// Effect is generated on auxiliary actuator, e.g. seat belt tensioner.
		public const int Aux1       = 1 << 4;

		// Effect is generated on auxiliary actuator, e.g. seat belt tensioner.
		public const int Aux2       = 1 << 5;
	};
}
